import {
  Item, Category, Unit, Department, Store, Supplier,
  StockLedgerEntry, StockInReceipt, MaterialIssue, MaterialReturn,
  StockTransfer, StockAdjustment, MonthlyClosing, AlertNotification,
  AuditLog, UserRole, CompanySettings
} from '../types';
import { calculateWeightedAverageRate, getItemInventoryStatus } from '../utils/calculations';

// Key for LocalStorage
const STORAGE_KEY = 'ims_automation_yajur_data_v1';

export interface AppState {
  items: Item[];
  categories: Category[];
  units: Unit[];
  departments: Department[];
  stores: Store[];
  suppliers: Supplier[];
  ledger: StockLedgerEntry[];
  stockInReceipts: StockInReceipt[];
  materialIssues: MaterialIssue[];
  materialReturns: MaterialReturn[];
  stockTransfers: StockTransfer[];
  stockAdjustments: StockAdjustment[];
  monthlyClosings: MonthlyClosing[];
  alerts: AlertNotification[];
  auditLogs: AuditLog[];
  users: UserRole[];
  settings: CompanySettings;
  activeStoreId: string;
  activeUser: UserRole;
  isOfflineMode: boolean;
  isFirebaseSynced: boolean;
}

export const initialCategories: Category[] = [
  { id: 'cat-1', code: 'CAT-001', name: 'Mechanical', description: 'Mechanical spares, bearings, and parts', active: true },
  { id: 'cat-2', code: 'CAT-002', name: 'Electrical', description: 'Electrical consumables, fuses, and modules', active: true },
  { id: 'cat-3', code: 'CAT-003', name: 'Lubricants', description: 'Oil, grease, and lubrication items', active: true },
  { id: 'cat-4', code: 'CAT-004', name: 'Safety', description: 'PPE and safety consumables', active: true },
  { id: 'cat-5', code: 'CAT-005', name: 'Consumables', description: 'General industrial consumables & cotton waste', active: true }
];

export const initialUnits: Unit[] = [
  { id: 'u-1', code: 'PCS', name: 'Pieces', decimalAllowed: false, active: true },
  { id: 'u-2', code: 'KG', name: 'Kilograms', decimalAllowed: true, active: true },
  { id: 'u-3', code: 'LTR', name: 'Liters', decimalAllowed: true, active: true },
  { id: 'u-4', code: 'PAIR', name: 'Pairs', decimalAllowed: false, active: true },
  { id: 'u-5', code: 'MTR', name: 'Meters', decimalAllowed: true, active: true },
  { id: 'u-6', code: 'SET', name: 'Sets', decimalAllowed: false, active: true }
];

export const initialDepartments: Department[] = [
  { id: 'dep-1', code: 'DEP-01', name: 'Mechanical', departmentHead: 'R. Das', costCentre: 'CC-MECH', active: true },
  { id: 'dep-2', code: 'DEP-02', name: 'Electrical', departmentHead: 'S. Roy', costCentre: 'CC-ELEC', active: true },
  { id: 'dep-3', code: 'DEP-03', name: 'Production', departmentHead: 'A. Singh', costCentre: 'CC-PROD', active: true },
  { id: 'dep-4', code: 'DEP-04', name: 'Quality', departmentHead: 'P. Shah', costCentre: 'CC-QA', active: true },
  { id: 'dep-5', code: 'DEP-05', name: 'Admin & Stores', departmentHead: 'M. Ghosh', costCentre: 'CC-ADM', active: true }
];

export const initialStores: Store[] = [
  { id: 'str-1', code: 'STR-01', name: 'Main Store', responsiblePerson: 'M. Ghosh', location: 'Central Block', address: 'Central Warehouse, Gate 2', active: true }
];

export const initialSuppliers: Supplier[] = [
  { id: 'sup-1', code: 'SUP-001', name: 'ABC Bearings Pvt Ltd', contactPerson: 'Amit Patel', email: 'info@abcbearings.com', phone: '+91 98220 12345', address: '12, GIDC Industrial Estate, Vadodara, Gujarat', leadTimeDays: 15, preferred: true, active: true },
  { id: 'sup-2', code: 'SUP-002', name: 'Eastern Lubes', contactPerson: 'Rajesh Sen', email: 'sales@easternlubes.com', phone: '+91 98300 54321', address: 'Plot 45, Salt Lake Sector V, Kolkata, WB', leadTimeDays: 7, preferred: true, active: true },
  { id: 'sup-3', code: 'SUP-003', name: 'Industrial Safety Co.', contactPerson: 'Vikram Shah', email: 'contracts@indus-safety.com', phone: '+91 98450 98765', address: '55, Peenya Industrial Area, Bengaluru, Karnataka', leadTimeDays: 5, preferred: true, active: true }
];

export const initialItems: Item[] = [
  {
    id: 'itm-1',
    itemCode: 'ITM-0001',
    itemName: 'Bearing 6205',
    shortName: '6205 Bearing',
    description: 'Deep groove ball bearing 25x52x15 mm',
    categoryId: 'cat-1',
    categoryName: 'Mechanical',
    unitId: 'u-1',
    unitName: 'PCS',
    departmentId: 'dep-1',
    departmentName: 'Mechanical',
    defaultStoreId: 'str-1',
    defaultStoreName: 'Main Store',
    preferredSupplierId: 'sup-1',
    preferredSupplierName: 'ABC Bearings Pvt Ltd',
    partNumber: '6205-2RS',
    brand: 'SKF',
    specification: '25x52x15 mm',
    rack: 'A02',
    bin: 'B06',
    minStock: 10,
    maxStock: 60,
    reorderLevel: 20,
    reorderQty: 30,
    safetyFactor: 25,
    safetyStock: 10,
    leadTimeDays: 15,
    avgDailyConsumption: 2,
    avgMonthlyConsumption: 60,
    standardRate: 1600,
    lastPurchaseRate: 1620,
    averageRate: 1610,
    criticalItem: true,
    consumable: true,
    active: true,
    currentQty: 8,
    reservedQty: 0,
    availableQty: 8,
    stockValue: 12880,
    lastReceiptDate: '2026-09-02',
    lastIssueDate: '2026-09-07',
    createdAt: '2026-01-10',
    updatedAt: '2026-09-07'
  },
  {
    id: 'itm-2',
    itemCode: 'ITM-0002',
    itemName: 'Lubricant ABC',
    shortName: 'Lube ABC',
    description: 'High performance ISO VG 68 gear oil',
    categoryId: 'cat-3',
    categoryName: 'Lubricants',
    unitId: 'u-3',
    unitName: 'LTR',
    departmentId: 'dep-1',
    departmentName: 'Mechanical',
    defaultStoreId: 'str-1',
    defaultStoreName: 'Main Store',
    preferredSupplierId: 'sup-2',
    preferredSupplierName: 'Eastern Lubes',
    partNumber: 'VG68-50L',
    brand: 'Shell',
    rack: 'C01',
    bin: 'D02',
    minStock: 100,
    maxStock: 500,
    reorderLevel: 350,
    reorderQty: 200,
    safetyFactor: 20,
    safetyStock: 80,
    leadTimeDays: 7,
    avgDailyConsumption: 10,
    avgMonthlyConsumption: 300,
    standardRate: 180,
    lastPurchaseRate: 180,
    averageRate: 180,
    criticalItem: false,
    consumable: true,
    active: true,
    currentQty: 900,
    reservedQty: 0,
    availableQty: 900,
    stockValue: 162000,
    lastReceiptDate: '2026-08-18',
    lastIssueDate: '2026-09-02',
    createdAt: '2026-02-01',
    updatedAt: '2026-09-07'
  },
  {
    id: 'itm-3',
    itemCode: 'ITM-0003',
    itemName: 'Cotton Waste',
    shortName: 'Cotton Waste',
    description: 'White cotton cleaning waste for machinery',
    categoryId: 'cat-5',
    categoryName: 'Consumables',
    unitId: 'u-2',
    unitName: 'KG',
    departmentId: 'dep-3',
    departmentName: 'Production',
    defaultStoreId: 'str-1',
    defaultStoreName: 'Main Store',
    rack: 'E04',
    bin: 'B01',
    minStock: 50,
    maxStock: 600,
    reorderLevel: 175,
    reorderQty: 340,
    safetyFactor: 25,
    safetyStock: 35,
    leadTimeDays: 7,
    avgDailyConsumption: 20,
    avgMonthlyConsumption: 600,
    standardRate: 170,
    lastPurchaseRate: 170,
    averageRate: 170,
    criticalItem: false,
    consumable: true,
    active: true,
    currentQty: 200,
    reservedQty: 0,
    availableQty: 200,
    stockValue: 34000,
    lastReceiptDate: '2026-08-25',
    lastIssueDate: '2026-09-06',
    createdAt: '2026-01-15',
    updatedAt: '2026-09-07'
  },
  {
    id: 'itm-4',
    itemCode: 'ITM-0004',
    itemName: 'Spare Gearbox',
    shortName: 'Gearbox Assembly',
    description: 'Helical reduction gearbox 1:15 ratio',
    categoryId: 'cat-1',
    categoryName: 'Mechanical',
    unitId: 'u-1',
    unitName: 'PCS',
    departmentId: 'dep-1',
    departmentName: 'Mechanical',
    defaultStoreId: 'str-1',
    defaultStoreName: 'Main Store',
    preferredSupplierId: 'sup-1',
    preferredSupplierName: 'ABC Bearings Pvt Ltd',
    rack: 'R10',
    bin: 'A01',
    minStock: 1,
    maxStock: 2,
    reorderLevel: 1,
    reorderQty: 1,
    safetyFactor: 10,
    safetyStock: 1,
    leadTimeDays: 30,
    avgDailyConsumption: 0.005,
    avgMonthlyConsumption: 0.1,
    standardRate: 160000,
    lastPurchaseRate: 160000,
    averageRate: 160000,
    criticalItem: true,
    consumable: false,
    active: true,
    currentQty: 2,
    reservedQty: 0,
    availableQty: 2,
    stockValue: 320000,
    lastReceiptDate: '2026-01-12',
    lastIssueDate: undefined, // Non-moving
    createdAt: '2026-01-12',
    updatedAt: '2026-09-07'
  },
  {
    id: 'itm-5',
    itemCode: 'ITM-0005',
    itemName: 'Fuse 63A',
    shortName: '63A HRC Fuse',
    description: 'HRC Fuse link 63A 415V AC',
    categoryId: 'cat-2',
    categoryName: 'Electrical',
    unitId: 'u-1',
    unitName: 'PCS',
    departmentId: 'dep-2',
    departmentName: 'Electrical',
    defaultStoreId: 'str-3',
    defaultStoreName: 'Electrical Store',
    rack: 'E02',
    bin: 'F04',
    minStock: 15,
    maxStock: 120,
    reorderLevel: 25,
    reorderQty: 50,
    safetyFactor: 20,
    safetyStock: 8,
    leadTimeDays: 10,
    avgDailyConsumption: 2,
    avgMonthlyConsumption: 60,
    standardRate: 150,
    lastPurchaseRate: 150,
    averageRate: 150,
    criticalItem: false,
    consumable: true,
    active: true,
    currentQty: 74,
    reservedQty: 0,
    availableQty: 74,
    stockValue: 11100,
    lastReceiptDate: '2026-09-01',
    lastIssueDate: '2026-09-05',
    createdAt: '2026-02-10',
    updatedAt: '2026-09-07'
  },
  {
    id: 'itm-6',
    itemCode: 'ITM-0006',
    itemName: 'Safety Gloves',
    shortName: 'Leather Gloves',
    description: 'Heavy duty leather safety hand gloves',
    categoryId: 'cat-4',
    categoryName: 'Safety',
    unitId: 'u-4',
    unitName: 'PAIR',
    departmentId: 'dep-3',
    departmentName: 'Production',
    defaultStoreId: 'str-1',
    defaultStoreName: 'Main Store',
    preferredSupplierId: 'sup-3',
    preferredSupplierName: 'Industrial Safety Co.',
    rack: 'S01',
    bin: 'G03',
    minStock: 20,
    maxStock: 200,
    reorderLevel: 90,
    reorderQty: 180,
    safetyFactor: 25,
    safetyStock: 30,
    leadTimeDays: 5,
    avgDailyConsumption: 12,
    avgMonthlyConsumption: 360,
    standardRate: 85,
    lastPurchaseRate: 85,
    averageRate: 85,
    criticalItem: true,
    consumable: true,
    active: true,
    currentQty: 0,
    reservedQty: 0,
    availableQty: 0,
    stockValue: 0,
    lastReceiptDate: '2026-07-15',
    lastIssueDate: '2026-09-04',
    createdAt: '2026-01-20',
    updatedAt: '2026-09-07'
  },
  {
    id: 'itm-7',
    itemCode: 'ITM-0007',
    itemName: 'V-Belt B72',
    shortName: 'B72 Belt',
    description: 'Classical raw edge V-belt B72 section',
    categoryId: 'cat-1',
    categoryName: 'Mechanical',
    unitId: 'u-1',
    unitName: 'PCS',
    departmentId: 'dep-1',
    departmentName: 'Mechanical',
    defaultStoreId: 'str-1',
    defaultStoreName: 'Main Store',
    rack: 'A05',
    bin: 'V02',
    minStock: 5,
    maxStock: 50,
    reorderLevel: 12,
    reorderQty: 25,
    safetyFactor: 20,
    safetyStock: 4,
    leadTimeDays: 10,
    avgDailyConsumption: 1,
    avgMonthlyConsumption: 30,
    standardRate: 530,
    lastPurchaseRate: 530,
    averageRate: 530,
    criticalItem: false,
    consumable: true,
    active: true,
    currentQty: 18,
    reservedQty: 0,
    availableQty: 18,
    stockValue: 9540,
    lastReceiptDate: '2026-08-20',
    lastIssueDate: '2026-09-07',
    createdAt: '2026-03-01',
    updatedAt: '2026-09-07'
  },
  {
    id: 'itm-8',
    itemCode: 'ITM-0008',
    itemName: 'Cable Tie 200mm',
    shortName: 'Nylon Cable Tie',
    description: 'Nylon cable zip tie 200mm x 4.8mm black',
    categoryId: 'cat-2',
    categoryName: 'Electrical',
    unitId: 'u-1',
    unitName: 'PCS',
    departmentId: 'dep-2',
    departmentName: 'Electrical',
    defaultStoreId: 'str-1',
    defaultStoreName: 'Main Store',
    rack: 'E01',
    bin: 'T02',
    minStock: 50,
    maxStock: 1000,
    reorderLevel: 200,
    reorderQty: 500,
    safetyFactor: 20,
    safetyStock: 50,
    leadTimeDays: 5,
    avgDailyConsumption: 15,
    avgMonthlyConsumption: 450,
    standardRate: 3.5,
    lastPurchaseRate: 3.5,
    averageRate: 3.5,
    criticalItem: false,
    consumable: true,
    active: true,
    currentQty: -20,
    reservedQty: 0,
    availableQty: -20,
    stockValue: -70,
    lastReceiptDate: '2026-07-10',
    lastIssueDate: '2026-09-01',
    createdAt: '2026-02-15',
    updatedAt: '2026-09-07'
  },
  {
    id: 'itm-9',
    itemCode: 'ITM-0009',
    itemName: 'Gland 25mm',
    shortName: 'Brass Gland 25mm',
    description: 'Double compression brass cable gland 25mm',
    categoryId: 'cat-2',
    categoryName: 'Electrical',
    unitId: 'u-1',
    unitName: 'PCS',
    departmentId: 'dep-2',
    departmentName: 'Electrical',
    defaultStoreId: 'str-3',
    defaultStoreName: 'Electrical Store',
    minStock: 10,
    maxStock: 100,
    reorderLevel: 20,
    reorderQty: 40,
    safetyFactor: 20,
    safetyStock: 5,
    leadTimeDays: 7,
    avgDailyConsumption: 2,
    avgMonthlyConsumption: 60,
    standardRate: 340,
    lastPurchaseRate: 340,
    averageRate: 340,
    criticalItem: false,
    consumable: true,
    active: true,
    currentQty: -12,
    reservedQty: 0,
    availableQty: -12,
    stockValue: -4080,
    lastReceiptDate: '2026-06-20',
    lastIssueDate: '2026-09-03',
    createdAt: '2026-02-18',
    updatedAt: '2026-09-07'
  },
  {
    id: 'itm-10',
    itemCode: 'ITM-0010',
    itemName: 'Seal 45mm',
    shortName: 'Oil Seal 45mm',
    description: 'NBR double lip oil seal 45x65x10 mm',
    categoryId: 'cat-1',
    categoryName: 'Mechanical',
    unitId: 'u-1',
    unitName: 'PCS',
    departmentId: 'dep-1',
    departmentName: 'Mechanical',
    defaultStoreId: 'str-2',
    defaultStoreName: 'Mechanical Store',
    minStock: 5,
    maxStock: 50,
    reorderLevel: 15,
    reorderQty: 30,
    safetyFactor: 25,
    safetyStock: 5,
    leadTimeDays: 10,
    avgDailyConsumption: 1,
    avgMonthlyConsumption: 30,
    standardRate: 1430,
    lastPurchaseRate: 1430,
    averageRate: 1430,
    criticalItem: true,
    consumable: true,
    active: true,
    currentQty: -10,
    reservedQty: 0,
    availableQty: -10,
    stockValue: -14300,
    lastReceiptDate: '2026-05-10',
    lastIssueDate: '2026-09-04',
    createdAt: '2026-01-28',
    updatedAt: '2026-09-07'
  },
  {
    id: 'itm-11',
    itemCode: 'ITM-0011',
    itemName: 'PLC Module X2',
    shortName: 'PLC Input Card',
    description: '16 Channel Digital Input PLC Expansion Module',
    categoryId: 'cat-2',
    categoryName: 'Electrical',
    unitId: 'u-1',
    unitName: 'PCS',
    departmentId: 'dep-2',
    departmentName: 'Electrical',
    defaultStoreId: 'str-1',
    defaultStoreName: 'Main Store',
    minStock: 1,
    maxStock: 3,
    reorderLevel: 1,
    reorderQty: 1,
    safetyFactor: 15,
    safetyStock: 1,
    leadTimeDays: 20,
    avgDailyConsumption: 0.001,
    avgMonthlyConsumption: 0.03,
    standardRate: 76000,
    lastPurchaseRate: 76000,
    averageRate: 76000,
    criticalItem: true,
    consumable: false,
    active: true,
    currentQty: 1,
    reservedQty: 0,
    availableQty: 1,
    stockValue: 76000,
    lastReceiptDate: '2026-04-15',
    lastIssueDate: undefined, // Received but not issued
    createdAt: '2026-04-15',
    updatedAt: '2026-09-07'
  },
  {
    id: 'itm-12',
    itemCode: 'ITM-0012',
    itemName: 'Old Motor Coupling',
    shortName: 'Jaw Coupling',
    description: 'Flexible jaw coupling size 110 steel hub',
    categoryId: 'cat-1',
    categoryName: 'Mechanical',
    unitId: 'u-1',
    unitName: 'PCS',
    departmentId: 'dep-1',
    departmentName: 'Mechanical',
    defaultStoreId: 'str-1',
    defaultStoreName: 'Main Store',
    minStock: 2,
    maxStock: 10,
    reorderLevel: 3,
    reorderQty: 5,
    safetyFactor: 20,
    safetyStock: 2,
    leadTimeDays: 14,
    avgDailyConsumption: 0.01,
    avgMonthlyConsumption: 0.3,
    standardRate: 28000,
    lastPurchaseRate: 28000,
    averageRate: 28000,
    criticalItem: false,
    consumable: false,
    active: true,
    currentQty: 3,
    reservedQty: 0,
    availableQty: 3,
    stockValue: 84000,
    lastReceiptDate: '2026-02-05',
    lastIssueDate: '2026-03-10', // 180+ idle days
    createdAt: '2026-02-05',
    updatedAt: '2026-09-07'
  }
];

export const initialLedger: StockLedgerEntry[] = [
  {
    id: 'led-1',
    transactionDate: '2026-09-01',
    transactionType: 'OPENING',
    referenceNumber: 'AUG-CLOSE',
    itemId: 'itm-1',
    itemCode: 'ITM-0001',
    itemName: 'Bearing 6205',
    storeId: 'str-1',
    storeName: 'Main Store',
    inwardQty: 0,
    outwardQty: 0,
    runningQty: 44,
    rate: 1605,
    inwardValue: 0,
    outwardValue: 0,
    runningStockValue: 70620,
    userId: 'u-admin',
    userName: 'Admin User',
    timestamp: '2026-09-01T08:00:00Z'
  },
  {
    id: 'led-2',
    transactionDate: '2026-09-02',
    transactionType: 'STOCK_IN',
    referenceNumber: 'GRN-121',
    itemId: 'itm-1',
    itemCode: 'ITM-0001',
    itemName: 'Bearing 6205',
    storeId: 'str-1',
    storeName: 'Main Store',
    inwardQty: 50,
    outwardQty: 0,
    runningQty: 94,
    rate: 1610,
    inwardValue: 80500,
    outwardValue: 0,
    runningStockValue: 151340,
    userId: 'u-store',
    userName: 'Store User',
    timestamp: '2026-09-02T10:15:00Z'
  },
  {
    id: 'led-3',
    transactionDate: '2026-09-04',
    transactionType: 'ISSUE',
    referenceNumber: 'ISS-329',
    itemId: 'itm-1',
    itemCode: 'ITM-0001',
    itemName: 'Bearing 6205',
    storeId: 'str-1',
    storeName: 'Main Store',
    departmentId: 'dep-1',
    departmentName: 'Mechanical',
    inwardQty: 0,
    outwardQty: 31,
    runningQty: 63,
    rate: 1610,
    inwardValue: 0,
    outwardValue: 49910,
    runningStockValue: 101430,
    userId: 'u-store',
    userName: 'Store User',
    timestamp: '2026-09-04T11:30:00Z'
  },
  {
    id: 'led-4',
    transactionDate: '2026-09-05',
    transactionType: 'TRANSFER_OUT',
    referenceNumber: 'TRF-043',
    itemId: 'itm-1',
    itemCode: 'ITM-0001',
    itemName: 'Bearing 6205',
    storeId: 'str-1',
    storeName: 'Main Store',
    inwardQty: 0,
    outwardQty: 20,
    runningQty: 43,
    rate: 1610,
    inwardValue: 0,
    outwardValue: 32200,
    runningStockValue: 69230,
    userId: 'u-store',
    userName: 'Store User',
    timestamp: '2026-09-05T14:20:00Z'
  },
  {
    id: 'led-5',
    transactionDate: '2026-09-06',
    transactionType: 'ADJUSTMENT_MINUS',
    referenceNumber: 'ADJ-018',
    itemId: 'itm-1',
    itemCode: 'ITM-0001',
    itemName: 'Bearing 6205',
    storeId: 'str-1',
    storeName: 'Main Store',
    inwardQty: 0,
    outwardQty: 5,
    runningQty: 38,
    rate: 1610,
    inwardValue: 0,
    outwardValue: 8050,
    runningStockValue: 61180,
    userId: 'u-admin',
    userName: 'Admin User',
    timestamp: '2026-09-06T16:11:00Z'
  },
  {
    id: 'led-6',
    transactionDate: '2026-09-07',
    transactionType: 'ISSUE',
    referenceNumber: 'ISS-341',
    itemId: 'itm-1',
    itemCode: 'ITM-0001',
    itemName: 'Bearing 6205',
    storeId: 'str-1',
    storeName: 'Main Store',
    departmentId: 'dep-1',
    departmentName: 'Mechanical',
    inwardQty: 0,
    outwardQty: 30,
    runningQty: 8,
    rate: 1610,
    inwardValue: 0,
    outwardValue: 48300,
    runningStockValue: 12880,
    userId: 'u-store',
    userName: 'Store User',
    timestamp: '2026-09-07T15:42:00Z'
  }
];

export const initialAlerts: AlertNotification[] = [
  {
    id: 'alt-1',
    severity: 'CRITICAL',
    title: 'Bearing 6205 Critical Stock',
    message: 'Bearing 6205 stock cover (4 days) is below supplier lead time (15 days). Immediate reorder required.',
    timestamp: '2 min ago',
    read: false,
    relatedItemId: 'itm-1'
  },
  {
    id: 'alt-2',
    severity: 'CRITICAL',
    title: 'Safety Gloves Out of Stock',
    message: 'Safety Gloves are currently out of stock (0 PAIR available). Last average daily consumption was 12 pairs.',
    timestamp: '18 min ago',
    read: false,
    relatedItemId: 'itm-6'
  },
  {
    id: 'alt-3',
    severity: 'WARNING',
    title: 'Lubricant ABC Overstock Warning',
    message: 'Lubricant ABC current stock (900 LTR) exceeds maximum stock level (500 LTR) by 400 LTR worth ₹72,000.',
    timestamp: '1 hr ago',
    read: false,
    relatedItemId: 'itm-2'
  },
  {
    id: 'alt-4',
    severity: 'WARNING',
    title: 'Spare Gearbox Non-Moving',
    message: 'Spare Gearbox has recorded no material issue for 240 days. Inventory value blocked: ₹3,20,000.',
    timestamp: '3 hrs ago',
    read: false,
    relatedItemId: 'itm-4'
  },
  {
    id: 'alt-5',
    severity: 'INFO',
    title: 'August 2026 Monthly Closing Open',
    message: 'August 2026 monthly closing status is still OPEN. Complete month-end audit before closing period.',
    timestamp: 'Today',
    read: true
  }
];

export const initialAuditLogs: AuditLog[] = [
  {
    id: 'aud-1',
    timestamp: '2026-09-07T16:11:00Z',
    time: '16:11',
    userId: 'u-admin',
    userName: 'Admin User',
    module: 'Stock Adjustment',
    action: 'POST',
    record: 'ADJ-019',
    previousValue: '105 PCS',
    newValue: '100 PCS',
    reason: 'Physical stock verification shortage (-5 PCS)'
  },
  {
    id: 'aud-2',
    timestamp: '2026-09-07T15:42:00Z',
    time: '15:42',
    userId: 'u-store',
    userName: 'Store User',
    module: 'Material Issue',
    action: 'POST',
    record: 'ISS-341',
    previousValue: '38 PCS',
    newValue: '8 PCS',
    reason: 'Mechanical department maintenance issue'
  },
  {
    id: 'aud-3',
    timestamp: '2026-09-07T14:21:00Z',
    time: '14:21',
    userId: 'u-admin',
    userName: 'Admin User',
    module: 'Item Master',
    action: 'UPDATE',
    record: 'ITM-0001',
    previousValue: 'Lead time 12d',
    newValue: 'Lead time 15d',
    reason: 'Supplier updated lead time parameters'
  },
  {
    id: 'aud-4',
    timestamp: '2026-09-07T12:10:00Z',
    time: '12:10',
    userId: 'u-store',
    userName: 'Store User',
    module: 'Stock In',
    action: 'POST',
    record: 'GRN-124',
    previousValue: '8 PCS',
    newValue: '58 PCS',
    reason: 'Inward material receipt posted against PO/2026-27/0237'
  }
];

export const initialUsers: UserRole[] = [
  {
    id: 'u-admin',
    name: 'Admin User',
    email: 'admin@yajurfibres.com',
    role: 'Super Admin',
    assignedStoreId: 'All Stores',
    status: 'Active',
    lastLogin: 'Today 16:15',
    mfaEnabled: true
  },
  {
    id: 'u-mgr',
    name: 'Store Manager',
    email: 'store.manager@yajurfibres.com',
    role: 'Store Manager',
    assignedStoreId: 'str-1',
    status: 'Active',
    lastLogin: 'Today 15:58',
    mfaEnabled: true
  },
  {
    id: 'u-store',
    name: 'Store User',
    email: 'store.user@yajurfibres.com',
    role: 'Store User',
    assignedStoreId: 'str-1',
    status: 'Active',
    lastLogin: 'Today 15:43',
    mfaEnabled: false
  },
  {
    id: 'u-viewer',
    name: 'Management Viewer',
    email: 'mis@yajurfibres.com',
    role: 'Viewer',
    assignedStoreId: 'All Stores',
    status: 'Active',
    lastLogin: 'Yesterday 18:20',
    mfaEnabled: false
  }
];

export const initialSettings: CompanySettings = {
  companyName: 'YAJUR FIBRES & TEXTILES LTD.',
  companyLogo: '',
  address: 'Plot 42, Industrial Growth Center, Sector 3, Phase II',
  gstReference: '24AAACY1234F1Z9',
  financialYearStart: 'April',
  currency: 'INR (₹)',
  defaultStoreId: 'str-1',
  valuationMethod: 'Weighted Average',
  enableNegativeStock: false,
  defaultLeadTimeDays: 7,
  defaultSafetyFactor: 25,
  reorderMethod: 'Lead Time + Safety Stock',
  nonMovingDays: 90,
  deadStockDays: 365,
  consumptionSpikeThreshold: 30,
  quantityPrecision: 2,
  monthlyCloseLock: true,
  darkMode: true
};

export function loadInitialState(): AppState {
  try {
    const saved = localStorage.getItem(STORAGE_KEY);
    if (saved) {
      const parsed = JSON.parse(saved);
      return {
        items: parsed.items || initialItems,
        categories: parsed.categories || initialCategories,
        units: parsed.units || initialUnits,
        departments: parsed.departments || initialDepartments,
        stores: parsed.stores || initialStores,
        suppliers: parsed.suppliers || initialSuppliers,
        ledger: parsed.ledger || initialLedger,
        stockInReceipts: parsed.stockInReceipts || [],
        materialIssues: parsed.materialIssues || [],
        materialReturns: parsed.materialReturns || [],
        stockTransfers: parsed.stockTransfers || [],
        stockAdjustments: parsed.stockAdjustments || [],
        monthlyClosings: parsed.monthlyClosings || [],
        alerts: parsed.alerts || initialAlerts,
        auditLogs: parsed.auditLogs || initialAuditLogs,
        users: parsed.users || initialUsers,
        settings: parsed.settings || initialSettings,
        activeStoreId: parsed.activeStoreId || 'str-1',
        activeUser: parsed.activeUser || initialUsers[0],
        isOfflineMode: false,
        isFirebaseSynced: true
      };
    }
  } catch (err) {
    console.error('Failed to load local storage state:', err);
  }

  return {
    items: initialItems,
    categories: initialCategories,
    units: initialUnits,
    departments: initialDepartments,
    stores: initialStores,
    suppliers: initialSuppliers,
    ledger: initialLedger,
    stockInReceipts: [],
    materialIssues: [],
    materialReturns: [],
    stockTransfers: [],
    stockAdjustments: [],
    monthlyClosings: [],
    alerts: initialAlerts,
    auditLogs: initialAuditLogs,
    users: initialUsers,
    settings: initialSettings,
    activeStoreId: 'str-1',
    activeUser: initialUsers[0],
    isOfflineMode: false,
    isFirebaseSynced: true
  };
}

export function saveStateToStorage(state: AppState): void {
  try {
    localStorage.setItem(STORAGE_KEY, JSON.stringify({
      items: state.items,
      categories: state.categories,
      units: state.units,
      departments: state.departments,
      stores: state.stores,
      suppliers: state.suppliers,
      ledger: state.ledger,
      stockInReceipts: state.stockInReceipts,
      materialIssues: state.materialIssues,
      materialReturns: state.materialReturns,
      stockTransfers: state.stockTransfers,
      stockAdjustments: state.stockAdjustments,
      monthlyClosings: state.monthlyClosings,
      alerts: state.alerts,
      auditLogs: state.auditLogs,
      users: state.users,
      settings: state.settings,
      activeStoreId: state.activeStoreId,
      activeUser: state.activeUser
    }));
  } catch (err) {
    console.error('Failed to save state to localStorage:', err);
  }
}
